const styles = {
  container: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '2rem 1rem',
  },
  header: {
    textAlign: 'center' as const,
    marginBottom: '3rem',
    padding: '2rem',
    background: 'linear-gradient(120deg, var(--ifm-color-primary-lightest) 0%, transparent 80%)',
    borderRadius: '1rem',
    border: '1px solid var(--ifm-color-primary-lighter)',
  },
  headerTitle: {
    fontSize: '2.5rem',
    fontWeight: 700,
    color: 'var(--ifm-color-primary-darker)',
    margin: '0 0 0.5rem 0',
  },
  headerSubtitle: {
    fontSize: '1.1rem',
    color: 'var(--ifm-color-primary-dark)',
    opacity: 0.8,
    margin: 0,
  },
  accessDenied: {
    textAlign: 'center' as const,
    padding: '3rem',
    color: '#b71c1c',
    background: 'rgba(255, 255, 255, 0.9)',
    borderRadius: '1rem',
    border: '1px solid #ffcdd2',
    maxWidth: 600,
    margin: '2rem auto',
  },
  accessDeniedTitle: {
    fontSize: '1.5rem',
    fontWeight: 700,
    marginBottom: '1rem',
  },
  accessDeniedText: {
    fontSize: '1rem',
    lineHeight: 1.6,
  },
  newCampaignSection: {
    margin: '2rem 0',
    textAlign: 'center' as const,
  },
  newCampaignButton: {
    fontSize: '1.1rem',
    padding: '0.8rem 2rem',
    borderRadius: '2rem',
    border: 'none',
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(22, 51, 124, 0.3)',
  },
  newCampaignButtonHover: {
    transform: 'translateY(-2px)',
    boxShadow: '0 6px 20px rgba(22, 51, 124, 0.4)',
  },
  formContainer: {
    margin: '1.5rem auto',
    maxWidth: 500,
    background: 'rgba(255, 255, 255, 0.9)',
    borderRadius: '1rem',
    padding: '2rem',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    border: '1px solid var(--ifm-color-primary-lightest)',
  },
  formTitle: {
    fontSize: '1.3rem',
    fontWeight: 700,
    color: 'var(--ifm-color-primary-darker)',
    marginBottom: '1.5rem',
    textAlign: 'center' as const,
  },
  formGroup: {
    marginBottom: '1.5rem',
  },
  formLabel: {
    fontWeight: 600,
    fontSize: '1rem',
    display: 'block',
    marginBottom: '0.5rem',
    color: 'var(--ifm-color-primary-dark)',
  },
  formInput: {
    width: '100%',
    fontSize: '1rem',
    padding: '0.8rem 1rem',
    borderRadius: '0.5rem',
    border: '1px solid var(--ifm-color-primary-lightest)',
    fontFamily: 'inherit',
    transition: 'all 0.3s ease',
  },
  formInputFocus: {
    borderColor: 'var(--ifm-color-primary)',
    boxShadow: '0 0 0 3px rgba(22, 51, 124, 0.1)',
  },
  formTextarea: {
    width: '100%',
    fontSize: '1rem',
    padding: '0.8rem 1rem',
    borderRadius: '0.5rem',
    border: '1px solid var(--ifm-color-primary-lightest)',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    minHeight: '120px',
    transition: 'all 0.3s ease',
  },
  radioGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.8rem',
  },
  radioOption: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
    padding: '0.5rem',
    borderRadius: '0.5rem',
    transition: 'all 0.3s ease',
  },
  radioOptionHover: {
    background: 'rgba(22, 51, 124, 0.05)',
  },
  radioInput: {
    margin: 0,
    accentColor: 'var(--ifm-color-primary)',
  },
  radioLabel: {
    fontSize: '0.95rem',
    color: 'var(--ifm-color-primary-dark)',
  },
  submitButton: {
    fontSize: '1rem',
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-dark) 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 2rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
    width: '100%',
  },
  submitButtonHover: {
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 15px rgba(22, 51, 124, 0.4)',
  },
  successMessage: {
    color: '#2e7d32',
    fontWeight: 600,
    fontSize: '1rem',
    marginTop: '1rem',
    padding: '1rem',
    background: 'rgba(76, 175, 80, 0.1)',
    borderRadius: '0.5rem',
    border: '1px solid rgba(76, 175, 80, 0.3)',
  },
  errorMessage: {
    color: '#b71c1c',
    fontWeight: 600,
    fontSize: '1rem',
    marginBottom: '1rem',
    padding: '1rem',
    background: 'rgba(244, 67, 54, 0.1)',
    borderRadius: '0.5rem',
    border: '1px solid rgba(244, 67, 54, 0.3)',
  },
  campaignsHeader: {
    fontSize: '1.5rem',
    fontWeight: 700,
    marginBottom: '2rem',
    textAlign: 'center' as const,
    color: 'var(--ifm-color-primary-darker)',
  },
  loadingContainer: {
    textAlign: 'center' as const,
    padding: '3rem',
  },
  campaignCard: {
    background: 'rgba(255, 255, 255, 0.9)',
    borderRadius: '1rem',
    marginBottom: '1rem',
    padding: '1.5rem',
    boxShadow: '0 2px 12px rgba(0, 0, 0, 0.1)',
    border: '1px solid var(--ifm-color-primary-lightest)',
    transition: 'all 0.3s ease',
  },
  campaignCardHover: {
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
  },
  campaignTitle: {
    fontWeight: 700,
    fontSize: '1.2rem',
    marginBottom: '0.8rem',
    color: 'var(--ifm-color-primary-darker)',
  },
  campaignDescription: {
    fontSize: '1rem',
    marginBottom: '1rem',
    lineHeight: 1.6,
    whiteSpace: 'pre-line' as const,
    color: 'var(--ifm-color-primary-darkest)',
  },
  campaignMeta: {
    fontSize: '0.9rem',
    color: 'var(--ifm-color-primary-dark)',
    marginBottom: '1rem',
    padding: '0.8rem 1rem',
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: '0.5rem',
    border: '1px solid var(--ifm-color-primary-lightest)',
  },
  // --- Campaign Buttons ---
  signButton: {
    background: 'linear-gradient(135deg, #2196f3 0%, #1565c0 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.5rem 1.5rem',
    fontWeight: 600,
    cursor: 'pointer',
    margin: '0.5rem 0',
    transition: 'all 0.2s',
  },
  anonymousButton: {
    background: 'linear-gradient(135deg, #bdbdbd 0%, #757575 100%)',
    color: '#fff',
  },
  disabledButton: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  publicButton: {
    background: 'linear-gradient(135deg, #43a047 0%, #2e7d32 100%)',
    color: '#fff',
  },
  // --- Confirm Modal ---
  overlay: {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    background: 'rgba(0,0,0,0.3)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal: {
    background: '#fff',
    borderRadius: '1rem',
    padding: '2rem',
    minWidth: 320,
    maxWidth: 400,
    boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
    zIndex: 1001,
  },
  body: {
    fontSize: '1rem',
    marginBottom: '1.5rem',
    color: 'var(--ifm-color-primary-dark)',
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
  },
  button: {
    padding: '0.5rem 1.5rem',
    borderRadius: '0.5rem',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    fontSize: '1rem',
    transition: 'all 0.2s',
  },
  cancel: {
    background: '#bdbdbd',
    color: '#fff',
  },
  confirm: {
    background: 'linear-gradient(135deg, #ff9800 0%, #f57c00 100%)',
    color: '#fff',
  },
  disabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  // --- Campaign Review & Cards ---
  errorContainer: {
    color: '#b71c1c',
    fontWeight: 600,
    textAlign: 'center' as const,
    marginBottom: '1.5rem',
    padding: '1.5rem',
    background: 'rgba(255, 235, 238, 0.9)',
    borderRadius: '1rem',
    border: '1px solid #ffcdd2',
  },
  emptyContainer: {
    textAlign: 'center' as const,
    color: 'var(--ifm-color-primary-dark)',
    padding: '3rem',
    background: 'rgba(255, 255, 255, 0.8)',
    borderRadius: '1rem',
    border: '1px solid var(--ifm-color-primary-lighter)',
  },
  emptyIcon: {
    fontSize: '3rem',
    marginBottom: '1rem',
    opacity: 0.6,
  },
  layoutContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(500px, 1fr))',
    gap: '2rem',
    direction: 'rtl' as const,
  },
  sectionContainer: {
    background: 'rgba(255, 255, 255, 0.8)',
    borderRadius: '1rem',
    padding: '1.5rem',
    border: '1px solid var(--ifm-color-primary-lightest)',
  },
  sectionHeader: {
    fontSize: '1.2rem',
    fontWeight: 600,
    marginBottom: '1.5rem',
    padding: '1rem 1.5rem',
    borderRadius: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  unsignedHeader: {
    background: 'linear-gradient(135deg, rgba(33, 150, 243, 0.1) 0%, rgba(33, 150, 243, 0.05) 100%)',
    color: '#1565c0',
    border: '1px solid rgba(33, 150, 243, 0.3)',
  },
  signedHeader: {
    background: 'linear-gradient(135deg, rgba(76, 175, 80, 0.1) 0%, rgba(76, 175, 80, 0.05) 100%)',
    color: '#2e7d32',
    border: '1px solid rgba(76, 175, 80, 0.3)',
  },
  emptySection: {
    textAlign: 'center' as const,
    color: 'var(--ifm-color-primary-dark)',
    padding: '2rem',
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: '0.5rem',
    border: '1px solid var(--ifm-color-primary-lightest)',
  },
  mobileLayout: {
    display: 'none',
    direction: 'rtl' as const,
  },
  // --- Campaign Header ---
  campaignHeader: {
    fontSize: '1.5rem',
    fontWeight: 700,
    marginBottom: '2rem',
    textAlign: 'center' as const,
    color: 'var(--ifm-color-primary-darker)',
  },
  campaignDate: {
    fontSize: '0.9rem',
    color: 'var(--ifm-color-primary-dark)',
    marginBottom: '1rem',
  },
  campaignType: {
    fontSize: '0.9rem',
    color: 'var(--ifm-color-primary-dark)',
    marginBottom: '1rem',
  },
  anonymousType: {
    color: '#b71c1c',
  },
  publicType: {
    color: '#43a047',
  },
  campaignEmail: {
    fontSize: '1rem',
    color: 'var(--ifm-color-primary-darkest)',
    marginBottom: '1rem',
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1rem',
    marginTop: '2rem',
  },
  approveButton: {
    background: 'linear-gradient(135deg, #43a047 0%, #2e7d32 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 2rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
  rejectButton: {
    background: 'linear-gradient(135deg, #ff9800 0%, #f57c00 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 2rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
  // --- Stats ---
  statsContainer: {
    display: 'flex',
    justifyContent: 'space-around',
    marginTop: '2rem',
    padding: '1rem',
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: '0.5rem',
    border: '1px solid var(--ifm-color-primary-lightest)',
  },
  statItem: {
    textAlign: 'center',
  },
  statNumber: {
    fontSize: '1.8rem',
    fontWeight: 700,
    color: 'var(--ifm-color-primary-darker)',
    marginBottom: '0.5rem',
  },
  statLabel: {
    fontSize: '0.9rem',
    color: 'var(--ifm-color-primary-dark)',
  },
  // --- Campaigns List ---
  campaignsContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '1.5rem',
    marginTop: '2rem',
  },
  accessDeniedRole: {
    color: '#b71c1c',
    fontWeight: 600,
  },
  headerIcon: {
    fontSize: '1.5rem',
    marginRight: '0.5rem',
  },
  pdfPreview: {
    maxWidth: '100%',
    height: 'auto',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.1)',
  },
  closeButton: {
    position: 'absolute',
    top: '1rem',
    right: '1rem',
    background: 'transparent',
    border: 'none',
    fontSize: '1.5rem',
    cursor: 'pointer',
    color: 'var(--ifm-color-primary-darker)',
  },
  mainList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  managerBox: {
    background: 'rgba(255, 255, 255, 0.9)',
    borderRadius: '1rem',
    padding: '1.5rem',
    boxShadow: '0 2px 12px rgba(0, 0, 0, 0.1)',
    border: '1px solid var(--ifm-color-primary-lightest)',
    marginBottom: '1rem',
  },
  managerButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.8rem 1.5rem',
    borderRadius: '0.5rem',
    border: 'none',
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
  managerIcon: {
    fontSize: '1.2rem',
    color: '#fff',
  },
  editorBlock: {
    marginBottom: '1.5rem',
  },
  editorButton: {
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 1.5rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
  editorButtonGray: {
    background: '#f0f0f0',
    color: 'var(--ifm-color-primary-darker)',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 1.5rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  },
  toggleIcon: {
    fontSize: '1.2rem',
    color: 'var(--ifm-color-primary-darker)',
    cursor: 'pointer',
    marginLeft: '0.5rem',
  },
  issuesList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  issueItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.8rem 1rem',
    borderRadius: '0.5rem',
    marginBottom: '0.5rem',
    background: 'rgba(255, 255, 255, 0.8)',
    border: '1px solid var(--ifm-color-primary-lightest)',
  },
  issueButton: {
    background: 'transparent',
    border: 'none',
    fontSize: '1rem',
    cursor: 'pointer',
    color: 'var(--ifm-color-primary-darker)',
  },
  issueIcon: {
    fontSize: '1.1rem',
    marginRight: '0.5rem',
  },
  issueMissing: {
    color: '#b71c1c',
    fontWeight: 600,
  },
  // --- Hero Section ---
  heroSection: {
    position: 'relative',
    height: '400px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(120deg, var(--ifm-color-primary-lightest) 0%, var(--ifm-color-primary-lighter) 100%)',
    borderRadius: '1rem',
    marginBottom: '2rem',
    overflow: 'hidden',
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: 'rgba(0, 0, 0, 0.5)',
    zIndex: 1,
  },
  heroContent: {
    position: 'relative',
    zIndex: 2,
    textAlign: 'center',
    color: '#fff',
  },
  heroTitle: {
    fontSize: '3.5rem',
    fontWeight: 800,
    marginBottom: '1rem',
    textShadow: '2px 2px 4px rgba(0, 0, 0, 0.3)',
  },
  heroSubtitle: {
    fontSize: '1.5rem',
    marginBottom: '2rem',
    textShadow: '1px 1px 2px rgba(0, 0, 0, 0.3)',
  },
  heroButtons: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1.5rem',
  },
  heroButton: {
    fontSize: '1.2rem',
    padding: '0.8rem 2.5rem',
    borderRadius: '2.5rem',
    border: 'none',
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(22, 51, 124, 0.3)',
  },
  primaryButton: {
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 2rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
  secondaryButton: {
    background: '#f0f0f0',
    color: 'var(--ifm-color-primary-darker)',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 2rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  },
  // --- Features Section ---
  featuresSection: {
    padding: '4rem 0',
    background: 'linear-gradient(120deg, var(--ifm-color-primary-lightest) 0%, var(--ifm-color-primary-lighter) 100%)',
    borderRadius: '1rem',
    marginBottom: '2rem',
  },
  featuresContainer: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '0 1rem',
  },
  sectionTitle: {
    fontSize: '2.5rem',
    fontWeight: 700,
    textAlign: 'center' as const,
    color: 'var(--ifm-color-primary-darker)',
    marginBottom: '3rem',
  },
  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '2rem',
  },
  featureCard: {
    background: 'rgba(255, 255, 255, 0.9)',
    borderRadius: '1rem',
    padding: '2rem',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    border: '1px solid var(--ifm-color-primary-lightest)',
    transition: 'all 0.3s ease',
  },
  featureImage: {
    width: '100%',
    height: '200px',
    objectFit: 'cover',
    borderRadius: '0.5rem',
    marginBottom: '1.5rem',
  },
  featureTitle: {
    fontSize: '1.3rem',
    fontWeight: 700,
    color: 'var(--ifm-color-primary-darker)',
    marginBottom: '1rem',
  },
  downloadLink: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    borderRadius: '0.5rem',
    padding: '0.8rem 1.5rem',
    fontWeight: 600,
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
  comingSoon: {
    fontSize: '1.1rem',
    color: 'var(--ifm-color-primary-dark)',
    opacity: 0.8,
  },
  // --- Quick Links Section ---
  quickLinksSection: {
    padding: '4rem 0',
    background: 'linear-gradient(120deg, var(--ifm-color-primary-lightest) 0%, var(--ifm-color-primary-lighter) 100%)',
    borderRadius: '1rem',
    marginBottom: '2rem',
  },
  quickLinksGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1.5rem',
  },
  quickLinkCard: {
    background: 'rgba(255, 255, 255, 0.9)',
    borderRadius: '1rem',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    border: '1px solid var(--ifm-color-primary-lightest)',
    transition: 'all 0.3s ease',
  },
  quickLinkIcon: {
    fontSize: '2rem',
    marginBottom: '1rem',
    color: 'var(--ifm-color-primary)',
  },
  quickLinkTitle: {
    fontSize: '1.2rem',
    fontWeight: 700,
    color: 'var(--ifm-color-primary-darker)',
    marginBottom: '0.5rem',
  },
  quickLinkDescription: {
    fontSize: '0.9rem',
    color: 'var(--ifm-color-primary-dark)',
    opacity: 0.8,
  },
  // --- User Section ---
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1rem',
  },
  themeToggle: {
    background: 'transparent',
    border: 'none',
    fontSize: '1.5rem',
    cursor: 'pointer',
    color: 'var(--ifm-color-primary-darker)',
  },
  userButton: {
    background: 'transparent',
    border: 'none',
    fontSize: '1.2rem',
    cursor: 'pointer',
    color: 'var(--ifm-color-primary-darker)',
  },
  userButtonHover: {
    color: 'var(--ifm-color-primary)',
  },
  adminBadge: {
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    borderRadius: '0.5rem',
    padding: '0.3rem 0.8rem',
    fontSize: '0.8rem',
    fontWeight: 600,
    marginLeft: '0.5rem',
  },
  dropdownArrow: {
    fontSize: '1rem',
    marginLeft: '0.5rem',
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    right: '0',
    background: '#fff',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    zIndex: 1002,
    minWidth: '150px',
    border: '1px solid var(--ifm-color-primary-lightest)',
  },
  dropdownItem: {
    padding: '0.8rem 1rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  dropdownItemHover: {
    background: 'rgba(22, 51, 124, 0.05)',
  },
  profileButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.8rem 1rem',
    borderRadius: '0.5rem',
    border: 'none',
    background: 'linear-gradient(135deg, var(--ifm-color-primary) 0%, var(--ifm-color-primary-light) 100%)',
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
  logoutButton: {
    background: 'linear-gradient(135deg, #ff9800 0%, #f57c00 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.5rem',
    padding: '0.8rem 1.5rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(22, 51, 124, 0.3)',
  },
};

export default styles; 